"""Generate M3 AEC constants directly from the nominated reference ELF."""
import struct
from pathlib import Path
from elftools.elf.elffile import ELFFile

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / 'inputs/reference/system/odm/lib64/libm256aecrelay.so'


def main():
    tables = {}
    with SOURCE.open('rb') as stream:
        elf = ELFFile(stream)
        for symbol in elf.get_section_by_name('.symtab').iter_symbols():
            name = symbol.name
            if not name.startswith('kM256M3') and name != 'kM256Aec17uShortLongDr':
                continue
            size, address = symbol['st_size'], symbol['st_value']
            section = elf.get_section(symbol['st_shndx'])
            offset = address - section['sh_addr']
            raw = section.data()[offset:offset + size]
            assert len(raw) == size and size % 4 == 0, name
            tables[name] = struct.unpack('<' + 'f' * (size // 4), raw)
    assert 'kM256Aec17uShortLongDr' in tables
    output = ['// Generated by decode_m3_aec_tables.py from libm256aecrelay.so.',
              '// Only tables consumed by the M3 luma/base/histogram paths.',
              '#pragma once', 'namespace m3_aec_tables {']
    for name, values in tables.items():
        output.append(f'inline constexpr float {name}[{len(values)}] = {{')
        for start in range(0, len(values), 8):
            output.append('    ' + ', '.join(v.hex() + 'f' for v in values[start:start + 8]) + ',')
        output.append('};')
    output.append('} // namespace m3_aec_tables')
    target = ROOT / 'native/m3_aec_tables.h'
    target.write_text('\n'.join(output) + '\n', encoding='utf-8')
    print('Generated', len(tables), 'M3 AEC tables:', target)


if __name__ == '__main__':
    main()
